### ISSUE TITLE
bug assuming lack of LB error means success

### ISSUE THREAD

**Issue by sam-github** [strongloop/strong-pm#130]
Which it doesn't:

```
sam@samtu:~/w/sn/strong-pm ((bfd413b...) $%) % ./bin/sl-pmctl.js -C http://localhost:8765 status                                                                                               

TypeError: Cannot call method 'create' of undefined
    at HttpInvocation.<anonymous> (/home/sam/w/sn/strong-pm/bin/sl-pmctl.js:473:22)
    at HttpInvocation.transformResponse (/home/sam/w/sn/strong-pm/node_modules/loopback/node_modules/strong-remoting/lib/http-invocation.js:271:12)
    at HttpInvocation.<anonymous> (/home/sam/w/sn/strong-pm/node_modules/loopback/node_modules/strong-remoting/lib/http-invocation.js:211:10)
    at Request.self.callback (/home/sam/w/sn/strong-pm/node_modules/request/request.js:373:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/sam/w/sn/strong-pm/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/sam/w/sn/strong-pm/node_modules/request/request.js:1266:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
```

Probably something else is broken, this is assuming that a service ID of 1 is always found.

**Comment by sam-github** [comment]
Cannot reproduce.

**Comment by rmg** [comment]
Wasn't this something you found in #128? Could it be specific to http+ssh?
