### ISSUE TITLE
pm dying in mesh models while log-dump running

### ISSUE THREAD

**Issue by sam-github** [strongloop/strong-pm#145]
I did an `npm install -g strongloop` while pm was running... I think that should do nothing, once pm is running, it shouldn't hit disk... but maybe it does?

```
sam@sambook:~ % slc pmctl log-dump --follow
......
2015-03-09T17:13:55.589Z pid:35684 worker:3 Browse your REST API at http://localhost:3000/explorer
2015-03-09T17:13:55.590Z pid:35684 worker:3 Web server listening at: http://localhost:3000/
2015-03-09T17:13:55.693Z pid:35685 worker:4 Sample data was imported.
2015-03-09T17:13:55.697Z pid:35685 worker:4 Browse your REST API at http://localhost:3000/explorer
2015-03-09T17:13:55.698Z pid:35685 worker:4 Web server listening at: http://localhost:3000/

assert.js:87
  throw new assert.AssertionError({
        ^
AssertionError: AccessToken is referencing a dataSource that does not exist: "memory"
    at configureModel (/usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback/lib/application.js:405:5)
    at EventEmitter.app.model (/usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback/lib/application.js:129:5)
    at /usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback-boot/lib/executor.js:166:9
    at Array.forEach (native)
    at setupModels (/usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback-boot/lib/executor.js:162:23)
    at execute (/usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback-boot/lib/executor.js:33:3)
    at bootLoopBackApp (/usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback-boot/index.js:129:3)
    at new Client (/usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/strong-mesh-models/client/client.js:30:3)
    at remoteHttpRequest (/usr/local/lib/node_modules/strongloop/node_modules/strong-pm/bin/sl-pmctl.js:463:16)
    at Immediate.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-pm/bin/sl-pmctl.js:458:5)
``

**Comment by sam-github** [comment]
I couldn't reproduce. Hm.

**Comment by rmg** [comment]
I _think_ this is caused by strong-pm starting its http server before it loads the loopback models used by that server. Perhaps the http server shouldn't be started until after everything is up and running?

**Comment by sam-github** [comment]
Hm, @kraman, comment on above?

**Comment by kraman** [comment]
@sam-github I havent been able to reproduce this issue. Any additional details?
