### ISSUE TITLE
strongloop process continuously restarting

### ISSUE THREAD

**Issue by bobgreen5s** [strongloop/strong-pm#205]
Hi, I noticed in /var/syslog that strong-pm was constantly exiting and restarting so I looked at the logs in /var/log/upstart/strong-pm.log and noticed the following error message repeating:

```
/usr/local/lib/node_modules/strong-pm/lib/service-manager.js:341
      metas[instance.id].size = instance.cpus;
                              ^
TypeError: Cannot set property 'size' of undefined
  at /usr/local/lib/node_modules/strong-pm/lib/service-manager.js:341:31
  at allCb (/usr/local/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback-datasource-juggler/lib/dao.js:1339:7)
  at /usr/local/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:371:7
  at process._tickDomainCallback (node.js:459:13)
  at process.<anonymous> (/usr/local/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)
```

Anyone have any ideas?

Any help would be appreciated
- Thanks, David

**Comment by sam-github** [comment]
That's a  bug we've found and fixed, I'll publish the fix.

**Comment by sam-github** [comment]
strong-pm@4.1.1 should fix this, can you please confirm?

**Comment by davidshepard989** [comment]
Looks like its all working now!

Thank for that extremely prompt fix, I really appreciate it.

**Comment by bobgreen5s** [comment]
Looks like its all working now!

Thank for that extremely prompt fix, I really appreciate it.
