### ISSUE TITLE
I am getting this error on every environment I try to setup on. 

### ISSUE THREAD

**Issue by chrisamoore** [strongloop/strong-pm#253]
I have tried this on a few basic Ubuntu images, and docker on a few machines. Seems pretty recent. Any help ? 
It definitely looks like a strong-pm error... perhaps the memory DB whilst creating the Models? 

/cc @rmg @ShubhraKar

```

╭─cmoore@cam17in.san.rr.com  ‹node-v2.3.1› ~/code
╰─ docker run \
  --publish 8701:8701 --publish 3000:3000 \
  --name strong-pm-container \
  strongloop/strong-pm

/usr/local/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback-datasource-juggler/lib/utils.js:381
        if (!target[key]) {
                   ^
TypeError: Cannot read property 'default' of null
    at /usr/local/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback-datasource-juggler/lib/utils.js:381:20
    at Array.forEach (native)
    at mergeSettings (/usr/local/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback-datasource-juggler/lib/utils.js:376:22)
    at Function.ModelClass.extend (/usr/local/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback-datasource-juggler/lib/model-builder.js:384:26)
    at Registry.createModel (/usr/local/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback/lib/registry.js:122:25)
    at /usr/local/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback-boot/lib/executor.js:214:24
    at Array.forEach (native)
    at defineModels (/usr/local/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback-boot/lib/executor.js:198:23)
    at setupModels (/usr/local/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback-boot/lib/executor.js:166:3)
    at execute (/usr/local/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback-boot/lib/executor.js:32:3)

```

**Comment by chrisamoore** [comment]
Ok confirmed it is reproducible on just the pm, using the built in pm of strongloop is funtional via an upstart command. So.... Ideas ?

**Comment by kraman** [comment]
@chrisamoore This was a bug in one of our dependencies. It has been resolved and updated as of yesterday evening. Please try your install again and let me know if this is still an issue.

**Comment by chrisamoore** [comment]
will verify & let you know.

**Comment by chrisamoore** [comment]
did you update the container? b/c I pulled latest & still fails.

**Comment by rmg** [comment]
The strongloop/strong-pm:latest image was rebuilt on the 10th with the following deps:
```
strong-pm@4.3.1 /usr/local/lib/node_modules/strong-pm
├── sl-blip@1.0.0
├── uid-number@0.0.5
├── strong-spawn-npm@1.0.0
├── chownr@0.0.1
├── strong-url-defaults@1.2.0
├── extsprintf@1.3.0
├── posix-getopt@1.1.0
├── async@0.9.2
├── osenv@0.1.3 (os-homedir@1.0.0, os-tmpdir@1.0.1)
├── debug@2.2.0 (ms@0.7.1)
├── serve-favicon@2.3.0 (fresh@0.3.0, etag@1.7.0, ms@0.7.1, parseurl@1.3.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── passwd-user@1.2.0 (exec-file-sync@1.0.0)
├── bl@0.9.4 (readable-stream@1.0.33)
├── strong-service-install@1.1.3 (strong-service-systemd@1.2.0, minimist@0.2.0, strong-service-upstart@1.1.0, shell-quote@1.4.3, which@1.1.1)
├── concat-stream@1.5.0 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.1)
├── strong-fork-cicada@1.1.2 (inherits@1.0.0, shell-quote@0.0.1, mkdirp@0.3.5, strong-fork-pushover@1.3.9)
├── compression@1.5.1 (bytes@2.1.0, vary@1.0.1, on-headers@1.0.0, compressible@2.0.4, accepts@1.2.10)
├── errorhandler@1.4.1 (escape-html@1.0.2, accepts@1.2.10)
├── rimraf@2.4.1 (glob@4.5.3)
├── tar@1.0.3 (inherits@2.0.1, block-stream@0.0.8, fstream@1.0.7)
├── express@4.13.1 (escape-html@1.0.2, fresh@0.3.0, vary@1.0.1, merge-descriptors@1.0.0, array-flatten@1.1.0, cookie@0.1.3, etag@1.7.0, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, parseurl@1.3.0, range-parser@1.0.2, path-to-regexp@0.1.6, content-type@1.0.1, content-disposition@0.5.0, serve-static@1.10.0, depd@1.0.1, qs@4.0.0, on-finished@2.3.0, finalhandler@0.4.0, proxy-addr@1.0.8, send@0.13.0, accepts@1.2.10, type-is@1.6.4)
├── strong-docker-build@1.1.0 (through@2.3.8, async@1.3.0, fstream-npm@1.0.4, tar@2.1.1)
├── dockerode@2.2.1 (docker-modem@0.2.5)
├── strong-npm-ls@1.0.5 (topiary@1.1.1, read-installed@3.1.5)
├── strong-tunnel@1.1.2 (ssh2@0.4.10)
├── express-ws@0.2.6 (url-join@0.0.1, ws@0.4.32)
├── http-auth@2.2.8 (node-uuid@1.4.1, htpasswd@2.2.0)
├── strong-control-channel@1.3.0 (newline-json@0.1.1, ws@0.7.2)
├── lodash@3.10.0
├── strong-runner@2.0.0 (npm-path@1.0.2, lodash@2.4.2, strong-supervisor@2.0.2)
├── strong-mesh-models@7.1.1 (user-home@1.1.1, sprintf@0.1.5, text-table@0.2.0, loopback-boot@2.8.2, request@2.58.0, loopback-datasource-juggler@2.33.0, loopback@2.19.0, loopback-explorer@1.8.0)
└── minkelite@1.1.2 (xtend@4.0.0, ago@1.0.0, stats-lite@1.0.3, MD5@1.2.2, util@0.10.3, body-parser@1.9.3, express@4.9.8, sqlite3@3.0.8)
```

**Comment by rmg** [comment]
@chrisamoore it looks like the latest strongloop/strong-pm image was built just _before_ the fixed dependency was published. I've kicked off another build, so it it should be available from docker hub soon.

**Comment by rmg** [comment]
strongloop/strong-pm:latest as of this writing (image id 00fbdfaa2fc0), includes the fixed dependency:
```
strong-pm@4.3.1 /usr/local/lib/node_modules/strong-pm
├── sl-blip@1.0.0
├── uid-number@0.0.5
├── strong-spawn-npm@1.0.0
├── chownr@0.0.1
├── strong-url-defaults@1.2.0
├── extsprintf@1.3.0
├── posix-getopt@1.1.0
├── async@0.9.2
├── debug@2.2.0 (ms@0.7.1)
├── osenv@0.1.3 (os-tmpdir@1.0.1, os-homedir@1.0.0)
├── serve-favicon@2.3.0 (fresh@0.3.0, ms@0.7.1, etag@1.7.0, parseurl@1.3.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── passwd-user@1.2.0 (exec-file-sync@1.0.0)
├── bl@0.9.4 (readable-stream@1.0.33)
├── concat-stream@1.5.0 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.1)
├── strong-service-install@1.1.3 (strong-service-systemd@1.2.0, minimist@0.2.0, strong-service-upstart@1.1.0, shell-quote@1.4.3, which@1.1.1)
├── compression@1.5.1 (bytes@2.1.0, vary@1.0.1, on-headers@1.0.0, compressible@2.0.4, accepts@1.2.10)
├── errorhandler@1.4.1 (escape-html@1.0.2, accepts@1.2.10)
├── strong-fork-cicada@1.1.2 (inherits@1.0.0, shell-quote@0.0.1, mkdirp@0.3.5, strong-fork-pushover@1.3.9)
├── rimraf@2.4.1 (glob@4.5.3)
├── tar@1.0.3 (inherits@2.0.1, block-stream@0.0.8, fstream@1.0.7)
├── express@4.13.1 (escape-html@1.0.2, fresh@0.3.0, vary@1.0.1, merge-descriptors@1.0.0, array-flatten@1.1.0, etag@1.7.0, cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, parseurl@1.3.0, methods@1.1.1, range-parser@1.0.2, path-to-regexp@0.1.6, content-type@1.0.1, content-disposition@0.5.0, serve-static@1.10.0, depd@1.0.1, qs@4.0.0, finalhandler@0.4.0, on-finished@2.3.0, proxy-addr@1.0.8, send@0.13.0, accepts@1.2.10, type-is@1.6.4)
├── strong-docker-build@1.1.0 (through@2.3.8, async@1.3.0, fstream-npm@1.0.4, tar@2.1.1)
├── dockerode@2.2.2 (docker-modem@0.2.6)
├── strong-npm-ls@1.0.5 (topiary@1.1.1, read-installed@3.1.5)
├── strong-tunnel@1.1.2 (ssh2@0.4.10)
├── http-auth@2.2.8 (node-uuid@1.4.1, htpasswd@2.2.0)
├── express-ws@0.2.6 (url-join@0.0.1, ws@0.4.32)
├── strong-control-channel@1.3.0 (newline-json@0.1.1, ws@0.7.2)
├── lodash@3.10.0
├── strong-runner@2.0.0 (npm-path@1.0.2, lodash@2.4.2, strong-supervisor@2.0.2)
├── minkelite@1.1.2 (xtend@4.0.0, ago@1.0.0, stats-lite@1.0.3, MD5@1.2.2, util@0.10.3, body-parser@1.9.3, express@4.9.8, sqlite3@3.0.8)
└── strong-mesh-models@7.1.1 (user-home@1.1.1, sprintf@0.1.5, text-table@0.2.0, loopback-boot@2.8.2, request@2.58.0, loopback-datasource-juggler@2.33.1, loopback-explorer@1.8.0, loopback@2.19.0)
```

**Comment by chrisamoore** [comment]
ty for the quick response, I will try this out, later on.

**Comment by chrisamoore** [comment]
:+1: Thanks good to go.
