### ISSUE TITLE
Upgraded to v5.0.0, strange issue when relaunching

### ISSUE THREAD

**Issue by notbrain** [strongloop/strong-pm#270]
Just upgraded to strong-pm 5.0.0 with full strongloop, but now can't respawn our apps. Seeing this in strong-pm.log repeated over and over again:

    SyntaxError: Unexpected end of input
        at Object.parse (native)
        at parseAndLoad (/usr/lib/node_modules/strongloop/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:122:21)
        at /usr/lib/node_modules/strongloop/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:108:9
        at fs.js:334:14
        at FSReqWrap.oncomplete (fs.js:95:15)
    Connection fails:  [SyntaxError: Unexpected end of input]
    It will be retried for the next request.
    Listening failed with: Unexpected end of input
    events.js:85
          throw er; // Unhandled 'error' event

Is this an error in strong-pm or the loopback-datasource-connector? Should this be filed over there?

**Comment by rmg** [comment]
Seems the Memory connector is failing while trying to load its file.. but I don't believe that is actually being used anymore..

When you performed the upgrade, what did you run? Did you stop the strong-pm service before running the installation?

**Comment by notbrain** [comment]
Yeah, that could have been it, I don't remember if I had shut down strong-pm or not. :/

**Comment by notbrain** [comment]
Seems to be what you suggested, my original troubleshooting began on an initial error happening on only a *single call* of our API, which was resulting in a strange error on User.verifyPassword(). Every other call was working fine. In hindsight this corresponded to the strongloop upgrade while strong-pm was running. To the best of my knowledge. Just leaving this here if anyone else has a similar issue.

    2015-08-06T20:49:55.548Z pid:21669 worker:4 Web server listening at: http://0.0.0.0:3003/
    2015-08-06T21:01:05.306Z pid:6940 worker:8 /var/lib/strong-pm/svc/3/work/33d0d862f97293c4b5a6845a79e4955c2823e10a.1438856458283/node_modules/loopback/common/models/user.js:530
    2015-08-06T21:01:05.306Z pid:6940 worker:8     throw err;
    2015-08-06T21:01:05.306Z pid:6940 worker:8           ^
    2015-08-06T21:01:05.306Z pid:6940 worker:8 Error: Invalid password: 
    2015-08-06T21:01:05.307Z pid:6940 worker:8     at Function.User.validatePassword (/var/lib/strong-pm/svc/3/work/33d0d862f97293c4b5a6845a79e4955c2823e10a.1438856458283/node_modules/loopback/common/models/user.js:528:16)
    2015-08-06T21:01:05.307Z pid:6940 worker:8     at Function.User.hashPassword (/var/lib/strong-pm/svc/3/work/33d0d862f97293c4b5a6845a79e4955c2823e10a.1438856458283/node_modules/loopback/common/models/user.js:519:10)
    2015-08-06T21:01:05.307Z pid:6940 worker:8     at ModelConstructor.UserModel.setter.password (/var/lib/strong-pm/svc/3/work/33d0d862f97293c4b5a6845a79e4955c2823e10a.1438856458283/node_modules/loopback/common/models/user.js:552:43)
    2015-08-06T21:01:05.307Z pid:6940 worker:8     at ModelConstructor.Object.defineProperty.set [as password] (/var/lib/strong-pm/svc/3/work/33d0d862f97293c4b5a6845a79e4955c2823e10a.1438856458283/node_modules/loopback-datasource-juggler/lib/model-builder.js:455:43)
    2015-08-06T21:01:05.307Z pid:6940 worker:8     at ModelConstructor.ModelBaseClass._initProperties (/var/lib/strong-pm/svc/3/work/33d0d862f97293c4b5a6845a79e4955c2823e10a.1438856458283/node_modules/loopback-datasource-juggler/lib/model.js:182:17)
    2015-08-06T21:01:05.307Z pid:6940 worker:8     at ModelConstructor.ModelBaseClass (/var/lib/strong-pm/svc/3/work/33d0d862f97293c4b5a6845a79e4955c2823e10a.1438856458283/node_modules/loopback-datasource-juggler/lib/model.js:49:8)
    2015-08-06T21:01:05.307Z pid:6940 worker:8     at ModelConstructor (/var/lib/strong-pm/svc/3/work/33d0d862f97293c4b5a6845a79e4955c2823e10a.1438856458283/node_modules/loopback-datasource-juggler/lib/model-builder.js:177:22)
    2015-08-06T21:01:05.307Z pid:6940 worker:8     at ModelConstructor (/var/lib/strong-pm/svc/3/work/33d0d862f97293c4b5a6845a79e4955c2823e10a.1438856458283/node_modules/loopback-datasource-juggler/lib/model-builder.js:177:22)
    2015-08-06T21:01:05.307Z pid:6940 worker:8     at ModelConstructor (/var/lib/strong-pm/svc/3/work/33d0d862f97293c4b5a6845a79e4955c2823e10a.1438856458283/node_modules/loopback-datasource-juggler/lib/model-builder.js:177:22)
    2015-08-06T21:01:05.307Z pid:6940 worker:8     at new ModelConstructor (/var/lib/strong-pm/svc/3/work/33d0d862f97293c4b5a6845a79e4955c2823e10a.1438856458283/node_modules/loopback-datasource-juggler/lib/model-builder.js:177:22)
    2015-08-06T21:01:05.320Z pid:15272 worker:0 ERROR supervisor worker id 8 (pid 6940) accidental exit with 1

**Comment by rmg** [comment]
Thanks for the followup, @notbrain :-)

Can this be closed then? I'm not sure there's much that can be done about this other then documenting that the strong-pm server needs to be shutdown before upgrading it.
