### ISSUE TITLE
local test project, slc start failed with Error: bind EADDRINUSE

### ISSUE THREAD

**Issue by agreatfool** [strongloop/strong-pm#276]
Hey guys,

I'm a newbie of strongloop. I just made a skeleton project with command `slc loopback`, then I ran the command `slc start`. But the command failed with `Error: bind EADDRINUSE`.

The dump message is:
```
slc start: StrongLoop PM v5.0.0 (API v6.1.0) on port `8701`
slc start: Applications on port `3000 + service ID`
Run request for commit "Cart/local-directory" on current (none)
Start Runner: commit Cart/local-directory
2015-09-09T14:19:06.551Z pid:88575 worker:0 INFO strong-agent v1.6.4 profiling app 'Cart' pid '88575'
2015-09-09T14:19:06.557Z pid:88575 worker:0 INFO strong-agent[88575] started profiling agent
2015-09-09T14:19:06.558Z pid:88575 worker:0 INFO supervisor starting (pid 88575)
2015-09-09T14:19:06.559Z pid:88575 worker:0 INFO strong-agent strong-agent using strong-cluster-control v2.1.2
2015-09-09T14:19:06.561Z pid:88575 worker:0 INFO supervisor reporting metrics to `internal:`
2015-09-09T14:19:06.569Z pid:88575 worker:0 INFO supervisor size set to 1
2015-09-09T14:19:06.612Z pid:88575 worker:0 INFO supervisor started worker 1 (pid 88576)
2015-09-09T14:19:06.613Z pid:88575 worker:0 INFO supervisor resized to 1
2015-09-09T14:19:06.836Z pid:88576 worker:1 ERROR supervisor failed to enable tracing
2015-09-09T14:19:06.861Z pid:88576 worker:1 INFO strong-agent v1.6.4 profiling app 'Cart' pid '88576'
2015-09-09T14:19:06.864Z pid:88576 worker:1 INFO strong-agent[88576] started profiling agent
2015-09-09T14:19:06.866Z pid:88576 worker:1 Did not start trace object on worker 1, license missing?
2015-09-09T14:19:07.664Z pid:88576 worker:1 ## agent:tracing licensing missing or invalid. Please verify your licenses in the Licenses page by running StrongLoop Arc by typing "slc arc --licenses" . If you have questions about your license or StrongLoop licensing please contact sales@strongloop.com.
2015-09-09T14:19:07.666Z pid:88576 worker:1 events.js:85
2015-09-09T14:19:07.666Z pid:88576 worker:1       throw er; // Unhandled 'error' event
2015-09-09T14:19:07.666Z pid:88576 worker:1             ^
2015-09-09T14:19:07.666Z pid:88576 worker:1 Error: bind EADDRINUSE
2015-09-09T14:19:07.666Z pid:88576 worker:1     at exports._errnoException (util.js:746:11)
2015-09-09T14:19:07.666Z pid:88576 worker:1     at cb (net.js:1205:33)
2015-09-09T14:19:07.666Z pid:88576 worker:1     at rr (cluster.js:592:14)
2015-09-09T14:19:07.666Z pid:88576 worker:1     at Worker.<anonymous> (cluster.js:563:9)
2015-09-09T14:19:07.666Z pid:88576 worker:1     at process.<anonymous> (cluster.js:692:8)
2015-09-09T14:19:07.666Z pid:88576 worker:1     at process.emit (events.js:129:20)
2015-09-09T14:19:07.666Z pid:88576 worker:1     at handleMessage (child_process.js:324:10)
2015-09-09T14:19:07.667Z pid:88576 worker:1     at Pipe.channel.onread (child_process.js:352:11)
2015-09-09T14:19:07.677Z pid:88575 worker:0 ERROR supervisor worker id 1 (pid 88576) accidental exit with 1
...
```

Could you please help me figure out the cause?

My env:
```
OSX 10.10.5
strongloop v5.0.0 (node v0.12.7)
├── strong-arc@1.8.1 (15814c0)
├── strong-build@2.0.4 (9294f54)
├── strong-deploy@3.0.0 (bee617c)
├── strong-mesh-models@8.0.0 (1b220f7)
├── strong-pm@5.0.0 (dbaa1a5)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.1 (b17cbc0)
├─┬ strong-supervisor@3.0.2 (539c0ce)
│ └── strong-agent@1.6.4
├── generator-loopback@1.11.0 (dec0654)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```

**Comment by agreatfool** [comment]
Fixed, just edited your server config file, and make attribute "host" from default "0.0.0.0" to "localhost".
And the error gone.

**Comment by cgole** [comment]
not a bug

**Comment by cgole** [comment]
@agreatfool, can I close this?

**Comment by agreatfool** [comment]
@cgole sure.
