### ISSUE TITLE
strong-pm install fails

### ISSUE THREAD

**Issue by cebor** [strongloop/strong-pm#278]
Got following errors while installing strong-pm:

node v4.1
npm v3.3.3
ubuntu 15.04

```syslog
sudo npm install -g strong-pm
npm WARN deprecated jsonstream@1.0.3: use JSONStream instead
/usr/bin/sl-pm -> /usr/lib/node_modules/strong-pm/bin/sl-pm.js
/usr/bin/sl-pmctl -> /usr/lib/node_modules/strong-pm/bin/sl-pmctl.js
/usr/bin/slpm -> /usr/lib/node_modules/strong-pm/bin/sl-pm.js
/usr/bin/slpmctl -> /usr/lib/node_modules/strong-pm/bin/sl-pmctl.js
/usr/bin/sl-pm-install -> /usr/lib/node_modules/strong-pm/bin/sl-pm-install.js

> bufferutil@1.1.0 install /usr/lib/node_modules/strong-pm/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/strong-pm/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:0:
../node_modules/nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:256:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:672:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../src/bufferutil.cc:10:0:
/home/felix/.node-gyp/4.1.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/felix/.node-gyp/4.1.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/felix/.node-gyp/4.1.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/felix/.node-gyp/4.1.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/bufferutil.cc:16:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:676:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
bufferutil.target.mk:92: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
make: Leaving directory '/usr/lib/node_modules/strong-pm/node_modules/bufferutil/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-28-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/strong-pm/node_modules/bufferutil
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! Linux 3.19.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "strong-pm"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/felix/npm-debug.log
```

**Comment by rmg** [comment]
@cebor did the installation actually fail? If so, then there would appear to be a bug in how npm@3.3.3 handles `optionalDependencies`.

If it did not fail, then these errors are safe to ignore and should go away once strongloop/strong-control-channel@3d30a1af7fb4423447fdcae9c00d9d6c784b55d0 makes it into a release.

**Comment by cebor** [comment]
yes it fails just after the update from node v0.12.7 -> 4.1 and npm v2.14.3 -> v3.3.3

**Comment by rmg** [comment]
I've just reproduced this with a fresh node-v4.1.0/npm-v3.3.3 install. The compilation failures are the same when doing `npm install strong-pm` vs. `npm install --global strong-pm`, but when doing it globally the errors become fatal for some reason.

I've reported this upstream as npm/npm#9685.

I hate to say it, but you should probably `npm install -g npm@2`.

**Comment by jdhiro** [comment]
Hm. I downgraded to npm@2.14.3 and I'm still getting install errors with strong-pm. Ubuntu 14.04, Node 4.1

```
do-user@kaehler:~$ sudo npm install -g strong-pm
 
> utf-8-validate@1.1.0 install /usr/lib/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:0:
../node_modules/nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:256:25: error: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:672:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../src/validation.cc:10:0:
/home/do-user/.node-gyp/4.1.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/do-user/.node-gyp/4.1.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/do-user/.node-gyp/4.1.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/do-user/.node-gyp/4.1.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/validation.cc:15:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:676:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/validation/src/validation.o] Error 1
make: Leaving directory `/usr/lib/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/utf-8-validate/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
System Linux 3.13.0-52-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
 
> bufferutil@1.1.0 install /usr/lib/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:0:
../node_modules/nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:256:25: error: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:672:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../src/bufferutil.cc:10:0:
/home/do-user/.node-gyp/4.1.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/do-user/.node-gyp/4.1.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/do-user/.node-gyp/4.1.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/do-user/.node-gyp/4.1.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/bufferutil.cc:16:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:676:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
make: Leaving directory `/usr/lib/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/bufferutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-52-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.1.0
ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
 
> heapdump@0.3.7 install /usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/heapdump
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/heapdump/build'
  CXX(target) Release/obj.target/addon/src/heapdump.o
  SOLINK_MODULE(target) Release/obj.target/addon.node
  COPY Release/addon.node
make: Leaving directory `/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/heapdump/build'
 
> modern-syslog@1.1.1 install /usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/modern-syslog
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/modern-syslog/build'
  CXX(target) Release/obj.target/core/core.o
  SOLINK_MODULE(target) Release/obj.target/core.node
  COPY Release/core.node
make: Leaving directory `/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/modern-syslog/build'
 
> strong-agent@2.0.1 install /usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/strong-agent
> node-gyp rebuild || exit 0

make: Entering directory `/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/strong-agent/build'
  CXX(target) Release/obj.target/strong-agent/src/strong-agent.o
  SOLINK_MODULE(target) Release/obj.target/strong-agent.node
  COPY Release/strong-agent.node
make: Leaving directory `/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/strong-agent/build'
 
> strong-debugger@1.0.0 install /usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/strong-debugger
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/strong-debugger/build'
  CXX(target) Release/obj.target/debugger/src/mutex-wrap.o
  CXX(target) Release/obj.target/debugger/src/debugger.o
  CXX(target) Release/obj.target/debugger/src/controller.o
  CXX(target) Release/obj.target/debugger/src/worker.o
  CXX(target) Release/obj.target/debugger/src/worker-bindings.o
  SOLINK_MODULE(target) Release/obj.target/debugger.node
  COPY Release/debugger.node
make: Leaving directory `/usr/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/strong-debugger/build'
npm WARN deprecated jsonstream@1.0.3: use JSONStream instead
/
> sqlite3@3.1.0 install /usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/usr/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node" is installed via remote
/usr/bin/sl-pm -> /usr/lib/node_modules/strong-pm/bin/sl-pm.js
/usr/bin/sl-pmctl -> /usr/lib/node_modules/strong-pm/bin/sl-pmctl.js
/usr/bin/slpm -> /usr/lib/node_modules/strong-pm/bin/sl-pm.js
/usr/bin/slpmctl -> /usr/lib/node_modules/strong-pm/bin/sl-pmctl.js
/usr/bin/sl-pm-install -> /usr/lib/node_modules/strong-pm/bin/sl-pm-install.js
strong-pm@5.0.0 /usr/lib/node_modules/strong-pm
├── sl-blip@1.0.0
├── strong-spawn-npm@1.0.0
├── userhome@1.0.0
├── posix-getopt@1.2.0
├── extsprintf@1.3.0
├── async@0.9.2
├── strong-url-defaults@1.2.0
├── debug@2.2.0 (ms@0.7.1)
├── serve-favicon@2.3.0 (etag@1.7.0, fresh@0.3.0, ms@0.7.1, parseurl@1.3.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── bl@0.9.4 (readable-stream@1.0.33)
├── concat-stream@1.5.0 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.2)
├── compression@1.5.2 (bytes@2.1.0, vary@1.0.1, on-headers@1.0.0, compressible@2.0.5, accepts@1.2.13)
├── errorhandler@1.4.2 (escape-html@1.0.2, accepts@1.2.13)
├── express@4.13.3 (escape-html@1.0.2, vary@1.0.1, etag@1.7.0, fresh@0.3.0, merge-descriptors@1.0.0, array-flatten@1.1.1, cookie@0.1.3, parseurl@1.3.0, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, content-type@1.0.1, path-to-regexp@0.1.7, serve-static@1.10.0, range-parser@1.0.2, content-disposition@0.5.0, depd@1.0.1, qs@4.0.0, on-finished@2.3.0, finalhandler@0.4.0, proxy-addr@1.0.8, accepts@1.2.13, type-is@1.6.8, send@0.13.0)
├── strong-service-install@2.0.0 (async@1.4.2, uid-number@0.0.5, chownr@0.0.2, minimist@1.2.0, shell-quote@1.4.3, strong-service-systemd@1.2.0, strong-service-upstart@1.1.0, which@1.1.2)
├── strong-fork-cicada@1.1.2 (inherits@1.0.2, shell-quote@0.0.1, mkdirp@0.3.5, strong-fork-pushover@1.3.9)
├── tar@1.0.3 (inherits@2.0.1, block-stream@0.0.8, fstream@1.0.8)
├── rimraf@2.4.3 (glob@5.0.14)
├── dockerode@2.2.2 (docker-modem@0.2.6)
├── strong-tunnel@1.1.3 (ssh2@0.4.11)
├── strong-docker-build@1.1.0 (async@1.4.2, through@2.3.8, tar@2.2.1, fstream-npm@1.0.5)
├── strong-control-channel@2.1.0 (newline-json@0.1.1, ws@0.7.2)
├── strong-npm-ls@1.0.6 (topiary@1.1.1, read-installed@3.1.5)
├── http-auth@2.2.8 (node-uuid@1.4.1, htpasswd@2.2.0)
├── lodash@3.10.1
├── strong-runner@4.0.0 (strong-supervisor@3.2.0)
├── strong-mesh-models@8.0.0 (sprintf@0.1.5, user-home@1.1.1, text-table@0.2.0, loopback-boot@2.12.2, loopback-datasource-juggler@2.40.1, request@2.63.0, loopback@2.22.1, loopback-explorer@1.8.0)
└── minkelite@1.2.4 (xtend@4.0.0, ago@1.0.0, stats-lite@1.0.3, util@0.10.3, md5@2.0.0, body-parser@1.9.3, express@4.9.8, sqlite3@3.1.0)
```

**Comment by rmg** [comment]
@jdhiro the errors you are seeing are in optional dependencies. The difference with npm@2 is that your installation finished successfully, even though some optional dependencies failed. With npm@3, those optional dependency failures were causing the entire installation to abort.

**Comment by jdhiro** [comment]
Ah, got it! Thanks @rmg

**Comment by johnmw** [comment]
Thanks from me as well @rmg. I'm not sure who is in charge of the documentation, but it might be nice to remove the instruction to use the latest version of node and instead put a note to use npm version 2 until this is resolved?
