### ISSUE TITLE
Local deploy failed: 'DIR/WHERE/MY/APP/IS` does not exist

### ISSUE THREAD

**Issue by Bohmaster** [strongloop/strong-pm#280]
It's the first time I get this error.

I've cloned the repository and installed dependencies. Then I've run "slc start" command

root@implicate:~/guay/GUAYFinal# slc start
Local deploy failed: `/root/guay/GUAYFinal` does not exist
assert.js:327
assert.ifError = function(err) { if (err) throw err; };
                                          ^

Error: HTTP error 400
    at Error (native)
    at /usr/lib/node_modules/strongloop/node_modules/strong-deploy/lib/post-json.js:65:16
    at ConcatStream.<anonymous> (/usr/lib/node_modules/strongloop/node_modules/strong-deploy/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:72:20)
    at ConcatStream.emit (events.js:166:7)
    at finishMaybe (/usr/lib/node_modules/strongloop/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at afterWrite (/usr/lib/node_modules/strongloop/node_modules/readable-stream/lib/_stream_writable.js:340:3)
    at /usr/lib/node_modules/strongloop/node_modules/readable-stream/lib/_stream_writable.js:327:9
    at doNTCallback0 (node.js:407:9)
    at process._tickDomainCallback (node.js:377:13)

**Comment by rmg** [comment]
Is there anything in `~/.strong-pm/start.log` (or where ever your `slc pm` output is being redirected if you started it manually)?

**Comment by HarishVara** [comment]
I am facing with the same problem...i have removed strong-pm and tried, but there is no fix.Can someone please help me with this issue?

**Comment by rmg** [comment]
@HarishVara can you give more details on what the error you are seeing is?

**Comment by HarishVara** [comment]
Error: HTTP error 400
    at /usr/local/lib/node_modules/strongloop/node_modules/strong-deploy/lib/post-json.js:72:16
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:91:20)
    at ConcatStream.emit (events.js:186:7)
    at finishMaybe (/usr/local/lib/node_modules/strongloop/node_modules/readable-stream/lib/_stream_writable.js:513:14)
    at afterWrite (/usr/local/lib/node_modules/strongloop/node_modules/readable-stream/lib/_stream_writable.js:395:3)
    at _combinedTickCallback (internal/process/next_tick.js:80:20)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by HarishVara** [comment]
I am getting this error while running the application using slc start
