### ISSUE TITLE
Unable to run strong-pm on Ubuntu 14.04 + Node 4.1.2 system

### ISSUE THREAD

**Issue by jdhiro** [strongloop/strong-pm#284]
With the recent Node 4 issues aside, I'm able to install strong-pm with no errors, using either npm 2 or 3.

However, I'm still unable to deploy to the machine, and my log is full of sqlite 3 errors:

```
Error: Cannot find module '/usr/local/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/minkelite/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
module.js:338
    throw err;
    ^
```

**Comment by jdhiro** [comment]
Not sure what caused this, but rebuilding my server resolved the problem. Closing issue.
