### ISSUE TITLE
How to start sails.js app with babel support?

### ISSUE THREAD

**Issue by bossyang** [strongloop/strong-pm#292]
I created a sails application by generator-sails-rest-api. It uses Babel. I can't start the app using "slc start".

**package.json**
```json
{
  "name": "api-demo",
  "version": "0.1.0",
  "main": "app.js",
  "dependencies": {
    "bluebird": "^3.0.5",
    "hoek": "^3.0.1",
    "lodash": "^3.10.1",
    "passport": "^0.3.0",
    "passport-jwt": "^1.2.1",
    "passport-local": "^1.0.0",
    "pluralize": "^1.2.1",
    "rc": "^1.1.2",
    "sails": "^0.11.2",
    "sails-disk": "^0.10.8",
    "sails-memory": "^0.10.5",
    "sails-mysql": "^0.11.0",
    "sails-service-cipher": "^3.1.0",
    "sails-service-hash": "^3.0.3"
  },
  "devDependencies": {
    "babel": "^5.8.23",
    "chai": "^3.3.0",
    "esdoc": "^0.4.1",
    "isparta": "3.1.0",
    "mocha": "^2.3.3",
    "sails-memory": "^0.10.5",
    "sinon": "^1.17.1"
  },
  "scripts": {
    "clean": "rm -rf ./.tmp",
    "debug": "babel-node debug app.js",
    "docs": "esdoc -c esdoc.json",
    "start": "babel-node app.js",
    "test": "babel-node node_modules/.bin/isparta cover _mocha",
    "console": "babel-node ./node_modules/.bin/sails console"
  }
}
````
**app.js**
````javascript
require('sails').lift(require('rc')('sails'));
````
**Error**
````
2015-11-10T07:34:36.611Z pid:13521 worker:2491 /home/bossyang/workspace/api-demo/config/blueprints.js:12
2015-11-10T07:34:36.612Z pid:13521 worker:2491 export default {
2015-11-10T07:34:36.612Z pid:13521 worker:2491 ^^^^^^
2015-11-10T07:34:36.612Z pid:13521 worker:2491 SyntaxError: Unexpected reserved word
2015-11-10T07:34:36.612Z pid:13521 worker:2491     at exports.runInThisContext (vm.js:53:16)
2015-11-10T07:34:36.612Z pid:13521 worker:2491     at Module._compile (module.js:414:25)
2015-11-10T07:34:36.612Z pid:13521 worker:2491     at Object.Module._extensions..js (module.js:442:10)
2015-11-10T07:34:36.612Z pid:13521 worker:2491     at Module.load (module.js:356:32)
2015-11-10T07:34:36.612Z pid:13521 worker:2491     at Function.Module._load (module.js:311:12)
2015-11-10T07:34:36.612Z pid:13521 worker:2491     at Module.require (module.js:366:17)
2015-11-10T07:34:36.612Z pid:13521 worker:2491     at Module.module.__proto__.require (/home/bossyang/.nvm/versions/node/v4.2.2/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-agent/lib/agent.js:185:42)
2015-11-10T07:34:36.612Z pid:13521 worker:2491     at require (module.js:385:17)
2015-11-10T07:34:36.612Z pid:13521 worker:2491     at /home/bossyang/workspace/api-demo/node_modules/include-all/index.js:129:29
2015-11-10T07:34:36.612Z pid:13521 worker:2491     at Array.forEach (native)
2015-11-10T07:34:36.612Z pid:13521 worker:2491     at requireAll (/home/bossyang/workspace/api-demo/node_modules/include-all/index.js:44:9)
2015-11-10T07:34:36.612Z pid:13521 worker:2491     at buildDictionary (/home/bossyang/workspace/api-demo/node_modules/sails-build-dictionary/index.js:68:14)
2015-11-10T07:34:36.612Z pid:13521 worker:2491     at Function.module.exports.aggregate (/home/bossyang/workspace/api-demo/node_modules/sails-build-dictionary/index.js:190:9)
2015-11-10T07:34:36.612Z pid:13521 worker:2491     at Array.loadOtherConfigFiles (/home/bossyang/workspace/api-demo/node_modules/sails/lib/hooks/moduleloader/index.js:164:27)
2015-11-10T07:34:36.612Z pid:13521 worker:2491     at /home/bossyang/workspace/api-demo/node_modules/sails/node_modules/async/lib/async.js:484:38
2015-11-10T07:34:36.612Z pid:13521 worker:2491     at _each (/home/bossyang/workspace/api-demo/node_modules/sails/node_modules/async/lib/async.js:46:13)
2015-11-10T07:34:36.625Z pid:15054 worker:0 ERROR supervisor worker id 2491 (pid 13521) accidental exit with 1
````

**Comment by sam-github** [comment]
`"start": "babel-node app.js",`

In order to run with our instrumentation, your main entry point must be a node.js script, not a shell script, and it must be javascript that can be run by node.

Your npm start script is a shell script, running babel-node, which then runs the app.js, which isn't yet valid node.js javascript, after trans-compiling it.

To run, you'll need a `prepublish` script that statically transpiles your es6 js into js that is runnable using whatever version of node you run.

**Comment by bossyang** [comment]
@sam-github got it. Thanks.

**Comment by bossyang** [comment]
After creating  a file using require hook, I can start the app by node. Not works with slc start. But *slc run start.js* works. 
````bash
node start.js
```` 

**start.js**
````javascript
require('babel-core/register');
require('./app.js');
````

**Comment by sam-github** [comment]
start.js is not among the guesses we make, use one of the supported options: https://github.com/strongloop/strong-supervisor/blob/master/bin/sl-run.txt#L5-L20

**Comment by bossyang** [comment]
@sam-github Thank you so much.
