### ISSUE TITLE
Strong-PM fails: pid:14757 worker:1 error: password authentication failed for user "USER"

### ISSUE THREAD

**Issue by pvijeh** [strongloop/strong-pm#303]
My loopback app fails to run on strong-pm. 

Here is what the logs look like: 

any ideas what could be causing this?

pvijeh@places-api:~$ sl-pm
sl-pm(14743): StrongLoop PM v5.1.0 (API v6.1.0) on port `8701`
sl-pm(14743): Base folder `/home/pvijeh/.strong-pm`
sl-pm(14743): Applications on port `3000 + service ID`
Browse your REST API at http://127.0.0.1:8701/explorer
Run request for commit "1/default" on current (none)
Start Runner: commit 1/default
2015-12-29T22:27:15.316Z pid:14752 worker:0 INFO strong-agent v2.0.2 profiling app 'placesAPI' pid '14752'
2015-12-29T22:27:15.337Z pid:14752 worker:0 INFO strong-agent[14752] started profiling agent
2015-12-29T22:27:15.343Z pid:14752 worker:0 INFO supervisor starting (pid 14752)
2015-12-29T22:27:15.349Z pid:14752 worker:0 INFO strong-agent strong-agent using strong-cluster-control v2.2.1
2015-12-29T22:27:15.357Z pid:14752 worker:0 INFO supervisor reporting metrics to `internal:`
2015-12-29T22:27:15.384Z pid:14752 worker:0 INFO strong-agent not profiling, agent metrics requires a valid license.
2015-12-29T22:27:15.386Z pid:14752 worker:0 Please contact sales@strongloop.com for assistance.
2015-12-29T22:27:15.409Z pid:14752 worker:0 INFO supervisor size set to 2
2015-12-29T22:27:15.607Z pid:14752 worker:0 INFO supervisor started worker 1 (pid 14757)
2015-12-29T22:27:15.896Z pid:14752 worker:0 INFO supervisor started worker 2 (pid 14762)
2015-12-29T22:27:15.897Z pid:14752 worker:0 INFO supervisor resized to 2
2015-12-29T22:27:17.249Z pid:14757 worker:1 INFO strong-agent v2.0.2 profiling app 'placesAPI' pid '14757'
2015-12-29T22:27:17.249Z pid:14757 worker:1 INFO strong-agent[14757] started profiling agent
2015-12-29T22:27:17.635Z pid:14762 worker:2 INFO strong-agent v2.0.2 profiling app 'placesAPI' pid '14762'
2015-12-29T22:27:17.651Z pid:14762 worker:2 INFO strong-agent[14762] started profiling agent
2015-12-29T22:27:21.047Z pid:14757 worker:1 INFO strong-agent not profiling, agent metrics requires a valid license.
2015-12-29T22:27:21.048Z pid:14757 worker:1 Please contact sales@strongloop.com for assistance.
2015-12-29T22:27:21.098Z pid:14757 worker:1 Connection fails:  { [error: password authentication failed for user "pvijeh"]
2015-12-29T22:27:21.099Z pid:14757 worker:1   name: 'error',
2015-12-29T22:27:21.100Z pid:14757 worker:1   length: 95,
2015-12-29T22:27:21.100Z pid:14757 worker:1   severity: 'FATAL',
2015-12-29T22:27:21.101Z pid:14757 worker:1   code: '28P01',
2015-12-29T22:27:21.102Z pid:14757 worker:1   detail: undefined,
2015-12-29T22:27:21.103Z pid:14757 worker:1   hint: undefined,
2015-12-29T22:27:21.103Z pid:14757 worker:1   position: undefined,
2015-12-29T22:27:21.104Z pid:14757 worker:1   internalPosition: undefined,
2015-12-29T22:27:21.104Z pid:14757 worker:1   internalQuery: undefined,
2015-12-29T22:27:21.104Z pid:14757 worker:1   where: undefined,
2015-12-29T22:27:21.105Z pid:14757 worker:1   schema: undefined,
2015-12-29T22:27:21.106Z pid:14757 worker:1   table: undefined,
2015-12-29T22:27:21.106Z pid:14757 worker:1   column: undefined,
2015-12-29T22:27:21.109Z pid:14757 worker:1   dataType: undefined,
2015-12-29T22:27:21.110Z pid:14757 worker:1   constraint: undefined,
2015-12-29T22:27:21.110Z pid:14757 worker:1   file: 'auth.c',
2015-12-29T22:27:21.112Z pid:14757 worker:1   line: '304',
2015-12-29T22:27:21.112Z pid:14757 worker:1   routine: 'auth_failed' }
2015-12-29T22:27:21.113Z pid:14757 worker:1 It will be retried for the next request.
2015-12-29T22:27:21.114Z pid:14757 worker:1 events.js:142
2015-12-29T22:27:21.115Z pid:14757 worker:1       throw er; // Unhandled 'error' event
2015-12-29T22:27:21.115Z pid:14757 worker:1       ^
2015-12-29T22:27:21.116Z pid:14757 worker:1 error: password authentication failed for user "pvijeh"
2015-12-29T22:27:21.116Z pid:14757 worker:1     at Connection.parseE (/home/pvijeh/.strong-pm/svc/1/work/aeb39b8ff6393282f657f3c1f703760c207e265c.1451426442510/node_modules/pg/lib/connection.js:539:11)
2015-12-29T22:27:21.118Z pid:14757 worker:1     at Connection.parseMessage (/home/pvijeh/.strong-pm/svc/1/work/aeb39b8ff6393282f657f3c1f703760c207e265c.1451426442510/node_modules/pg/lib/connection.js:366:17)
2015-12-29T22:27:21.123Z pid:14757 worker:1     at Socket.<anonymous> (/home/pvijeh/.strong-pm/svc/1/work/aeb39b8ff6393282f657f3c1f703760c207e265c.1451426442510/node_modules/pg/lib/connection.js:105:22)
2015-12-29T22:27:21.123Z pid:14757 worker:1     at emitOne (events.js:78:13)
2015-12-29T22:27:21.124Z pid:14757 worker:1     at Socket.emit (events.js:170:7)
2015-12-29T22:27:21.124Z pid:14757 worker:1     at readableAddChunk (_stream_readable.js:147:16)
2015-12-29T22:27:21.127Z pid:14757 worker:1     at Socket.Readable.push (_stream_readable.js:111:10)
2015-12-29T22:27:21.127Z pid:14757 worker:1     at TCP.onread (net.js:524:20)
2015-12-29T22:27:21.154Z pid:14752 worker:0 ERROR supervisor worker id 1 (pid 14757) accidental exit with 1
2015-12-29T22:27:23.054Z pid:14762 worker:2 INFO strong-agent not profiling, agent metrics requires a valid license.
2015-12-29T22:27:23.054Z pid:14762 worker:2 Please contact sales@strongloop.com for assistance.
2015-12-29T22:27:23.083Z pid:14762 worker:2 Web server listening at: http://0.0.0.0:3001
2015-12-29T22:27:23.085Z pid:14762 worker:2 Browse your REST API at http://0.0.0.0:3001/explorer
sl-pm: Service "1" listening on 0.0.0.0:3001
2015-12-29T22:27:23.206Z pid:14762 worker:2 Connection fails:  { [error: password authentication failed for user "pvijeh"]
2015-12-29T22:27:23.207Z pid:14762 worker:2   name: 'error',
2015-12-29T22:27:23.207Z pid:14762 worker:2   length: 95,
2015-12-29T22:27:23.208Z pid:14762 worker:2   severity: 'FATAL',
2015-12-29T22:27:23.209Z pid:14762 worker:2   code: '28P01',
2015-12-29T22:27:23.212Z pid:14762 worker:2   detail: undefined,
2015-12-29T22:27:23.212Z pid:14762 worker:2   hint: undefined,
2015-12-29T22:27:23.213Z pid:14762 worker:2   position: undefined,
2015-12-29T22:27:23.216Z pid:14762 worker:2   internalPosition: undefined,
2015-12-29T22:27:23.216Z pid:14762 worker:2   internalQuery: undefined,
2015-12-29T22:27:23.217Z pid:14762 worker:2   where: undefined,
2015-12-29T22:27:23.217Z pid:14762 worker:2   schema: undefined,
2015-12-29T22:27:23.224Z pid:14762 worker:2   table: undefined,
2015-12-29T22:27:23.226Z pid:14762 worker:2   column: undefined,
2015-12-29T22:27:23.226Z pid:14762 worker:2   dataType: undefined,
2015-12-29T22:27:23.226Z pid:14762 worker:2   constraint: undefined,
2015-12-29T22:27:23.227Z pid:14762 worker:2   file: 'auth.c',
2015-12-29T22:27:23.227Z pid:14762 worker:2   line: '304',
2015-12-29T22:27:23.227Z pid:14762 worker:2   routine: 'auth_failed' }
2015-12-29T22:27:23.228Z pid:14762 worker:2 It will be retried for the next request.
2015-12-29T22:27:23.228Z pid:14762 worker:2 events.js:142
2015-12-29T22:27:23.235Z pid:14762 worker:2       throw er; // Unhandled 'error' event
2015-12-29T22:27:23.236Z pid:14762 worker:2       ^
2015-12-29T22:27:23.236Z pid:14762 worker:2 error: password authentication failed for user "pvijeh"
2015-12-29T22:27:23.236Z pid:14762 worker:2     at Connection.parseE (/home/pvijeh/.strong-pm/svc/1/work/aeb39b8ff6393282f657f3c1f703760c207e265c.1451426442510/node_modules/pg/lib/connection.js:539:11)
2015-12-29T22:27:23.236Z pid:14762 worker:2     at Connection.parseMessage (/home/pvijeh/.strong-pm/svc/1/work/aeb39b8ff6393282f657f3c1f703760c207e265c.1451426442510/node_modules/pg/lib/connection.js:366:17)
2015-12-29T22:27:23.237Z pid:14762 worker:2     at Socket.<anonymous> (/home/pvijeh/.strong-pm/svc/1/work/aeb39b8ff6393282f657f3c1f703760c207e265c.1451426442510/node_modules/pg/lib/connection.js:105:22)
2015-12-29T22:27:23.238Z pid:14762 worker:2     at emitOne (events.js:78:13)
2015-12-29T22:27:23.239Z pid:14762 worker:2     at Socket.emit (events.js:170:7)
2015-12-29T22:27:23.240Z pid:14762 worker:2     at readableAddChunk (_stream_readable.js:147:16)
2015-12-29T22:27:23.240Z pid:14762 worker:2     at Socket.Readable.push (_stream_readable.js:111:10)
2015-12-29T22:27:23.240Z pid:14762 worker:2     at TCP.onread (net.js:524:20)
2015-12-29T22:27:23.253Z pid:14752 worker:0 ERROR supervisor worker id 2 (pid 14762) accidental exit with 1
2015-12-29T22:27:23.493Z pid:14752 worker:0 INFO supervisor started worker 3 (pid 14778)
2015-12-29T22:27:24.613Z pid:14778 worker:3 INFO strong-agent v2.0.2 profiling app 'placesAPI' pid '14778'
2015-12-29T22:27:24.625Z pid:14778 worker:3 INFO strong-agent[14778] started profiling agent
2015-12-29T22:27:25.782Z pid:14752 worker:0 INFO supervisor started worker 4 (pid 14783)
2015-12-29T22:27:25.783Z pid:14752 worker:0 INFO supervisor resized to 2
2015-12-29T22:27:27.298Z pid:14783 worker:4 INFO strong-agent v2.0.2 profiling app 'placesAPI' pid '14783'
2015-12-29T22:27:27.323Z pid:14783 worker:4 INFO strong-agent[14783] started profiling agent

**Comment by rmg** [comment]
That error message is from your app, failing to connect to your PostgreSQL database (as indicated by `node_modules/pg/lib/connection.js` in the stacktrace).

How was your app deployed? Did it get deployed without the credentials for your database?

**Comment by pvijeh** [comment]
I deployed the app using "slc build" followed by "slc deploy IPADDRESS" and
it said it was deployed successfully.

I have matching postgres users, databases and passwords on both my local
machine (where the app runs fine) and on the remote box.

Is there any way to test what postgres credentials the deployed app is
trying to use?

**Comment by rmg** [comment]
strong-pm doesn't know/care much about what that app does, so you would likely need to add some sort of logging to indicate the credentials being used. The error message suggests `pvijeh` is the username your app is trying to use.

**Comment by pvijeh** [comment]
hmmm,  thanks.

Where do the actual deployed files get saved when deployed via strong-pm?

**Comment by rmg** [comment]
In the logs you provided your app was deployed to `/home/pvijeh/.strong-pm/svc/1/work/aeb39b8ff6393282f657f3c1f703760c207e265c.1451426442510`
