### ISSUE TITLE
Converting circular structure to JSON Error

### ISSUE THREAD

**Issue by zim32** [strongloop/strong-pm#307]
Hello. Seems like a bug inside internal/child_process.js

**slc start**

```
Process Manager is attempting to run app `.`.

  To confirm it is started: slc ctl status adv-frontend
  To view the last logs: slc ctl log-dump adv-frontend
  To see more options: slc ctl -h
  To see metrics, the profilers and other diagnostic features run: slc arc

--- tail of /home/*****/.strong-pm/start.log ---
slc start(2211): StrongLoop PM v5.1.0 (API v6.1.0) on port `8701`
slc start(2211): Base folder `/home/*****/.strong-pm`
slc start(2211): Applications on port `3000 + service ID`
Browse your REST API at http://127.0.0.1:8701/explorer
Run request for commit "app/local-directory" on current (none)
Start Runner: commit app/local-directory
2016-01-13T09:16:28.541Z pid:2220 worker:0 INFO strong-agent native addon missing, install a compiler
2016-01-13T09:16:28.544Z pid:2220 worker:0 INFO strong-agent v2.0.2 profiling app 'adv-frontend' pid '2220'
2016-01-13T09:16:28.547Z pid:2220 worker:0 INFO strong-agent[2220] started profiling agent
2016-01-13T09:16:28.547Z pid:2220 worker:0 INFO supervisor starting (pid 2220)
2016-01-13T09:16:28.548Z pid:2220 worker:0 INFO strong-agent strong-agent using strong-cluster-control v2.2.1
2016-01-13T09:16:28.550Z pid:2220 worker:0 INFO supervisor reporting metrics to `internal:`
2016-01-13T09:16:28.558Z pid:2220 worker:0 INFO strong-agent not profiling, agent metrics requires a valid license.
2016-01-13T09:16:28.558Z pid:2220 worker:0 Please contact sales@strongloop.com for assistance.
2016-01-13T09:16:28.559Z pid:2220 worker:0 INFO supervisor size set to 1
2016-01-13T09:16:28.596Z pid:2220 worker:0 INFO supervisor started worker 1 (pid 2225)
2016-01-13T09:16:28.597Z pid:2220 worker:0 INFO supervisor resized to 1
2016-01-13T09:16:28.769Z pid:2225 worker:1 INFO strong-agent native addon missing, install a compiler
2016-01-13T09:16:28.770Z pid:2225 worker:1 INFO strong-agent v2.0.2 profiling app 'adv-frontend' pid '2225'
2016-01-13T09:16:28.772Z pid:2225 worker:1 INFO strong-agent[2225] started profiling agent
2016-01-13T09:16:28.871Z pid:2225 worker:1 INFO strong-agent not profiling, agent metrics requires a valid license.
2016-01-13T09:16:28.872Z pid:2225 worker:1 Please contact sales@strongloop.com for assistance.
slc start: Service "1" listening on 172.18.0.20:3000
2016-01-13T09:16:28.876Z pid:2225 worker:1 Example app listening on port 3000!
```

Then make some post requests and get error
**slc ctl log-dump adv-frontend**

```
2016-01-13T09:16:58.794Z pid:2225 worker:1 internal/child_process.js:586
2016-01-13T09:16:58.794Z pid:2225 worker:1     var string = JSON.stringify(message) + '\n';
2016-01-13T09:16:58.795Z pid:2225 worker:1                       ^
2016-01-13T09:16:58.795Z pid:2225 worker:1 TypeError: Converting circular structure to JSON
2016-01-13T09:16:58.795Z pid:2225 worker:1     at Object.stringify (native)
2016-01-13T09:16:58.795Z pid:2225 worker:1     at process.target._send (internal/child_process.js:586:23)
2016-01-13T09:16:58.796Z pid:2225 worker:1     at process.target.send (internal/child_process.js:507:12)
2016-01-13T09:16:58.796Z pid:2225 worker:1     at Worker.send (cluster.js:47:21)
2016-01-13T09:16:58.796Z pid:2225 worker:1     at Object.emit (/usr/lib/node_modules/strongloop/node_modules/strong-supervisor/lib/watcher.js:64:26)
2016-01-13T09:16:58.796Z pid:2225 worker:1     at Agent.<anonymous> (/usr/lib/node_modules/strongloop/node_modules/strong-supervisor/lib/watcher/agent-trace.js:14:12)
2016-01-13T09:16:58.796Z pid:2225 worker:1     at emitOne (events.js:77:13)
2016-01-13T09:16:58.796Z pid:2225 worker:1     at Agent.emit (events.js:169:7)
2016-01-13T09:16:58.796Z pid:2225 worker:1     at emitOne (events.js:77:13)
2016-01-13T09:16:58.797Z pid:2225 worker:1     at EventEmitter.emit (events.js:169:7)
2016-01-13T09:16:58.817Z pid:2220 worker:0 ERROR supervisor worker id 1 (pid 2225) accidental exit with 1
2016-01-13T09:17:00.892Z pid:2220 worker:0 INFO supervisor started worker 2 (pid 2248)
2016-01-13T09:17:00.893Z pid:2220 worker:0 INFO supervisor resized to 1
2016-01-13T09:17:01.105Z pid:2248 worker:2 INFO strong-agent native addon missing, install a compiler
2016-01-13T09:17:01.106Z pid:2248 worker:2 INFO strong-agent v2.0.2 profiling app 'adv-frontend' pid '2248'
2016-01-13T09:17:01.108Z pid:2248 worker:2 INFO strong-agent[2248] started profiling agent
2016-01-13T09:17:01.208Z pid:2248 worker:2 INFO strong-agent not profiling, agent metrics requires a valid license.
2016-01-13T09:17:01.208Z pid:2248 worker:2 Please contact sales@strongloop.com for assistance.
2016-01-13T09:17:01.211Z pid:2248 worker:2 Example app listening on port 3000!
```

**Comment by rmg** [comment]
Well that's a new one...

You appear to be running Linux, is that correct? And what version of node?

**Comment by zim32** [comment]
Linux 13a657bc299c 3.14.32-xxxx-grs-ipv6-64 #5 SMP Wed Sep 9 17:24:34 CEST 2015 x86_64 GNU/Linux

Node v4.2.4

**Comment by fcarreiro** [comment]
I'm also getting this.
* `Linux 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
* Node 4.5.0
* "mysql": "^2.11.1"

Interestingly, it started happening when I started using connection pooling in mysql. If I run it without SLC it runs ok. If I run it with SLC with 1 or more workers I get the same error.
