### ISSUE TITLE
Error when strong-pm starts

### ISSUE THREAD

**Issue by gausie** [strongloop/strong-pm#321]
I'm getting this error in the logs when strong-pm starts.

```
TypeError: Cannot read property 'error' of undefined
    at ChildProcess.<anonymous> (/usr/lib/node_modules/strong-pm/node_modules/strong-runner/lib/runner.js:99:17)
    at emitOne (events.js:90:13)
    at ChildProcess.emit (events.js:182:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickDomainCallback (node.js:430:17)
    at process.<anonymous> (/usr/lib/node_modules/strong-pm/node_modules/async-listener/index.js:19:15)
```

I've previously run strong-pm without any issues of this kind. I updated and reinstalled strong-pm, and rebooted the server but still continue to get this error put into the logs every time it tries to restart.

**Comment by gausie** [comment]
It turned out that this was because my "current" symlink pointed to a non-existent directory.
