### ISSUE TITLE
Building and deploying successfully, but not sure if it is running. 

### ISSUE THREAD

**Issue by alexxgathp** [strongloop/strong-pm#326]
I've been deploying loopback apps in an atypical manner, but decided to try out the strongloop arc and strong-pm.

I setup the strong-pm service on the production host, openSUSE 13.1.

I built and deployed successfully from tar.gz in arc.

I can see the controller and its explorer at 8701, but I do not see my API / app anywhere.

Plus, when looking at the status I get this (Notice the "disabled" part. Possibly indicates what I'm doing wrong):

``` sh
cmtqa:~ # /usr/bin/systemctl status strong-pm -l
strong-pm.service - StrongLoop Process Manager
   Loaded: loaded (/etc/systemd/system/strong-pm.service; disabled)
   Active: active (running) since Thu 2016-03-17 13:57:33 CDT; 3h 15min ago
 Main PID: 3802 (node)
   CGroup: /system.slice/strong-pm.service
           ââ3802 /usr/bin/node /usr/lib/node_modules/strong-pm/bin/sl-pm.js --listen 8701 --base /var/lib/strong-pm --base-port 3000 --driver direct

Mar 17 17:12:53 cmtqa node[3802]: Unexpected exit with 1 from Runner: commit default/npm-pack
Mar 17 17:12:54 cmtqa node[3802]: Start Runner: commit default/npm-pack
Mar 17 17:12:54 cmtqa node[3802]: Invalid app (app is not a file or a directory ), try `slr --help`.
Mar 17 17:12:54 cmtqa node[3802]: Unexpected exit with 1 from Runner: commit default/npm-pack
Mar 17 17:12:55 cmtqa node[3802]: Start Runner: commit default/npm-pack
Mar 17 17:12:56 cmtqa node[3802]: Invalid app (app is not a file or a directory ), try `slr --help`.
Mar 17 17:12:56 cmtqa node[3802]: Unexpected exit with 1 from Runner: commit default/npm-pack
Mar 17 17:12:57 cmtqa node[3802]: Start Runner: commit default/npm-pack
Mar 17 17:12:57 cmtqa node[3802]: Invalid app (app is not a file or a directory ), try `slr --help`.
Mar 17 17:12:57 cmtqa node[3802]: Unexpected exit with 1 from Runner: commit default/npm-pack
```

**Comment by alexxgathp** [comment]
I did an enable command... it says enabled instead of disabled, but the same error messages are showing, and I checked both 3000 and 3001. I'm not seeing anything a change...

**Comment by alexxgathp** [comment]
Additional detail: I do not see it listening on a port.
```sh
netstan -an | grep LISTEN

tcp        0      0 0.0.0.0:25300           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN
tcp        0      0 :::21                   :::*                    LISTEN
tcp        0      0 :::22                   :::*                    LISTEN
tcp        0      0 :::8701                 :::*                    LISTEN
```

**Comment by alexxgathp** [comment]
Okay, so I restarted the service. No error messages. I deploy it with Strongloop Arc from my local, then the errors return. Something with the deploy seems to be amiss.
```sh
cmtqa:~ # /usr/bin/systemctl status strong-pm -l
strong-pm.service - StrongLoop Process Manager
   Loaded: loaded (/etc/systemd/system/strong-pm.service; enabled)
   Active: active (running) since Thu 2016-03-17 17:35:22 CDT; 1min 1s ago
 Main PID: 61554 (node)
   CGroup: /system.slice/strong-pm.service
           ââ61554 /usr/bin/node /usr/lib/node_modules/strong-pm/bin/sl-pm.js --listen 8701 --base /var/lib/strong-pm --base-port 3000 --driver direct

Mar 17 17:35:24 cmtqa node[61554]: sl-pm.js(61554): StrongLoop PM v5.2.0 (API v6.1.0) on port `8701`
Mar 17 17:35:24 cmtqa node[61554]: sl-pm.js(61554): Base folder `/var/lib/strong-pm`
Mar 17 17:35:24 cmtqa node[61554]: sl-pm.js(61554): Applications on port `3000 + service ID`
Mar 17 17:35:24 cmtqa node[61554]: Browse your REST API at http://127.0.0.1:8701/explorer
cmtqa:~ # /usr/bin/systemctl status strong-pm -l
strong-pm.service - StrongLoop Process Manager
   Loaded: loaded (/etc/systemd/system/strong-pm.service; enabled)
   Active: active (running) since Thu 2016-03-17 17:35:22 CDT; 4min 30s ago
 Main PID: 61554 (node)
   CGroup: /system.slice/strong-pm.service
           ââ61554 /usr/bin/node /usr/lib/node_modules/strong-pm/bin/sl-pm.js --listen 8701 --base /var/lib/strong-pm --base-port 3000 --driver direct

Mar 17 17:39:48 cmtqa node[61554]: Start Runner: commit default/npm-pack
Mar 17 17:39:49 cmtqa node[61554]: Invalid app (app is not a file or a directory ), try `slr --help`.
Mar 17 17:39:49 cmtqa node[61554]: Unexpected exit with 1 from Runner: commit default/npm-pack
Mar 17 17:39:49 cmtqa node[61554]: Start Runner: commit default/npm-pack
Mar 17 17:39:50 cmtqa node[61554]: Start Runner: child 61754 commit default/npm-pack
Mar 17 17:39:50 cmtqa node[61554]: Invalid app (app is not a file or a directory ), try `slr --help`.
Mar 17 17:39:50 cmtqa node[61554]: Unexpected exit with 1 from Runner: commit default/npm-pack
Mar 17 17:39:51 cmtqa node[61554]: Start Runner: commit default/npm-pack
Mar 17 17:39:51 cmtqa node[61554]: Invalid app (app is not a file or a directory ), try `slr --help`.
Mar 17 17:39:51 cmtqa node[61554]: Unexpected exit with 1 from Runner: commit default/npm-pack
```

**Comment by alexxgathp** [comment]
I restarted the service, and then I tried using the command-line version, instead of arc.
slc build --git
slc deploy http://IPADDRESS:8701

The results, still no api seen on 3000 to 3002:
```sh
cmtqa:~ # /usr/bin/systemctl status strong-pm -l
strong-pm.service - StrongLoop Process Manager
   Loaded: loaded (/etc/systemd/system/strong-pm.service; enabled)
   Active: active (running) since Thu 2016-03-17 18:54:43 CDT; 7min ago
 Main PID: 10918 (node)
   CGroup: /system.slice/strong-pm.service
           ââ10918 /usr/bin/node /usr/lib/node_modules/strong-pm/bin/sl-pm.js --listen 8701 --base /var/lib/strong-pm --base-port 3000 --driver direct
           ââ10927 /usr/bin/node /usr/lib/node_modules/strong-pm/node_modules/strong-supervisor/bin/sl-run.js --cluster=CPU --control=ws://e79f7db8129214d5a67f8f6ffce566e3e1f5038e6a466918@127.0.0.1:8701/instance-control
           ââ12128 /usr/bin/node /usr/lib/node_modules/strong-pm/node_modules/strong-supervisor/bin/sl-run.js server/server.js

Mar 17 19:02:21 cmtqa node[10918]: 2016-03-18T00:02:21.161Z pid:12123 worker:231     at new StorageService (/var/lib/strong-pm/svc/2/work/a64a177e33aea8a4a8678af77572b3a70dab677b.1458258265330/node_modules/loopback-component-storage/lib/storage-service.js:29:25)
Mar 17 19:02:21 cmtqa node[10918]: 2016-03-18T00:02:21.161Z pid:12123 worker:231     at Object.exports.initialize (/var/lib/strong-pm/svc/2/work/a64a177e33aea8a4a8678af77572b3a70dab677b.1458258265330/node_modules/loopback-component-storage/lib/storage-connector.js:12:19)
Mar 17 19:02:21 cmtqa node[10918]: 2016-03-18T00:02:21.161Z pid:12123 worker:231     at DataSource.setup (/var/lib/strong-pm/svc/2/work/a64a177e33aea8a4a8678af77572b3a70dab677b.1458258265330/node_modules/loopback-datasource-juggler/lib/datasource.js:332:17)
Mar 17 19:02:21 cmtqa node[10918]: 2016-03-18T00:02:21.161Z pid:12123 worker:231     at new DataSource (/var/lib/strong-pm/svc/2/work/a64a177e33aea8a4a8678af77572b3a70dab677b.1458258265330/node_modules/loopback-datasource-juggler/lib/datasource.js:109:8)
Mar 17 19:02:21 cmtqa node[10918]: 2016-03-18T00:02:21.161Z pid:12123 worker:231     at Registry.createDataSource (/var/lib/strong-pm/svc/2/work/a64a177e33aea8a4a8678af77572b3a70dab677b.1458258265330/node_modules/loopback/lib/registry.js:349:12)
Mar 17 19:02:21 cmtqa node[10918]: 2016-03-18T00:02:21.161Z pid:12123 worker:231     at Function.loopback.createDataSource (/var/lib/strong-pm/svc/2/work/a64a177e33aea8a4a8678af77572b3a70dab677b.1458258265330/node_modules/loopback/lib/loopback.js:353:41)
Mar 17 19:02:21 cmtqa node[10918]: 2016-03-18T00:02:21.161Z pid:12123 worker:231     at Object.<anonymous> (/var/lib/strong-pm/svc/2/work/a64a177e33aea8a4a8678af77572b3a70dab677b.1458258265330/server/server.js:26:19)
Mar 17 19:02:21 cmtqa node[10918]: 2016-03-18T00:02:21.165Z pid:10927 worker:0 ERROR supervisor worker id 231 (pid 12123) accidental exit with 1
Mar 17 19:02:22 cmtqa node[10918]: 2016-03-18T00:02:22.266Z pid:10927 worker:0 INFO supervisor started worker 232 (pid 12128)
Mar 17 19:02:22 cmtqa node[10918]: 2016-03-18T00:02:22.539Z pid:12128 worker:232 INFO strong-agent[12128] started profiling agent
```

**Comment by bistmaster** [comment]
you can check the status of the api by "slc ctl --control http://IPAddress status" or "slc ctl --control http://IPAddress ls"
