### ISSUE TITLE
Failed to start StrongLoop Arc

### ISSUE THREAD

**Issue by chuyik** [strongloop/strong-pm#356]
Versions:
Strongloop: v6.0.1
Node: v6.2.1
OS: OSX 10.11

Full stacktrace:

```
$ slc arc

(node:51797) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Swagger: skipping unknown type "subscription".
Swagger: skipping unknown type "subscription".
Loading workspace /Users/edc/someproject
StrongLoop Arc is running here: http://localhost:50452/#/
/Users/edc/.nvm/versions/node/v6.2.1/lib/node_modules/strongloop/node_modules/loopback-workspace/server/connector.js:205
              f.data.optionalDependencies['loopback'];                                         ^

TypeError: Cannot read property 'loopback' of undefined
    at /Users/edc/.nvm/versions/node/v6.2.1/lib/node_modules/strongloop/node_modules/loopback-workspace/server/connector.js:205:42
    at /Users/edc/.nvm/versions/node/v6.2.1/lib/node_modules/strongloop/node_modules/loopback-workspace/node_modules/async/lib/async.js:52:16
    at Immediate.<anonymous> (/Users/edc/.nvm/versions/node/v6.2.1/lib/node_modules/strongloop/node_modules/loopback-workspace/node_modules/async/lib/async.js:1206:34)
    at Immediate._onImmediate (/Users/edc/.nvm/versions/node/v6.2.1/lib/node_modules/strongloop/node_modules/async-listener/glue.js:188:31)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

I have no idea what happened, any thoughts?

**Comment by mk0x9** [comment]
Installing `strongloop` as project's dev dependency helped to avoid this issue, but this should be either fixed/reflected in documentation.

**Comment by bhoomit** [comment]
@chuyik did you find any solution to this issue? @mk0x9's solution didn't work for me :(

**Comment by chuyik** [comment]
@bhoomit No, I choose to stick with PM2 instead.

**Comment by stormwin** [comment]
remove line` f.data.optionalDependencies['loopback']; `
or put optionalDependencies: {} in your package.json
i think optionalDependencies is deprecated long time ago, and removed in newer npm/node versions

**OR**
Make small patch
```javascript
var loopBackVersion = f.data.dependencies['loopback'] ||
              f.data.devDependencies['loopback'] ||
             (f.data.optionalDependencies && f.data.optionalDependencies['loopback']);
```
in your file:
`/Users/edc/.nvm/versions/node/v6.2.1/lib/node_modules/strongloop/node_modules/loopback-workspace/server/connector.js`
