### ISSUE TITLE
Connection/deploy over ssh refused, timeouted

### ISSUE THREAD

**Issue by cojack** [strongloop/strong-pm#390]
Hello,
I have a problem connect to server over ssh, as in docs I have done:
```
$ export SSH_USER=develop
$ export SSH_KEY=~/Projects/path/to/priv-key
$ slc ctl --control http+ssh://some.services.oktawave.com
```

Then I've got a response:

> The user model "User" is attached to an application that does not specify
whether other sessions should be invalidated when a password or
an email has changed. Session invalidation is important for security
reasons as it allows users to recover from various account breach
situations.
> We recommend turning this feature on by setting
"logoutSessionsOnSensitiveChanges" to true in
server/config.json (unless you have implemented your own solution
for token invalidation).
> We also recommend enabling "injectOptionsFromRemoteContext" in
User's settings (typically via common/models/*.json file).
This setting is required for the invalidation algorithm to keep 
the current session valid.
>
> /home/cojack/.nvm/versions/node/v7.3.0/lib/node_modules/strongloop/node_modules/strong-tunnel/lib/tunnel.js:51
        throw err;
        ^
>
>Error: (SSH) Channel open failure: Connection refused
    at SSH2Stream.onFailure (/home/cojack/.nvm/versions/node/v7.3.0/lib/node_modules/strongloop/node_modules/ssh2/lib/client.js:1068:13)
    at SSH2Stream.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/home/cojack/.nvm/versions/node/v7.3.0/lib/node_modules/strongloop/node_modules/ssh2-streams/lib/ssh.js:3423:10)
    at SSH2Stream._transform (/home/cojack/.nvm/versions/node/v7.3.0/lib/node_modules/strongloop/node_modules/ssh2-streams/lib/ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/home/cojack/.nvm/versions/node/v7.3.0/lib/node_modules/strongloop/node_modules/ssh2-streams/lib/ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at SSH2Stream.Writable.write (_stream_writable.js:247:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)

Any idea?
Thanks in advance.

BTW. connection over ssh to this server works like a charm, so this should be noticed at first place

**Comment by Sanbornzhang** [comment]
try to follow /var/log/upstart/strong-pm.log 
and exec `sl-pm` on tty
